# Generated by Django 2.2.2 on 2019-06-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='pics')),
                ('category', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('adpt', models.BooleanField(default=False)),
            ],
        ),
    ]
