# Generated by Django 2.2.2 on 2019-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petnote', '0003_auto_20190628_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='img',
            field=models.ImageField(upload_to='media/pics/'),
        ),
    ]
