# Generated by Django 2.2.2 on 2019-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petnote', '0004_auto_20190628_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
